var API_URL = 'https://api.forecast.io/forecast/245e43548516a03f6afd16e5bf31af69/';

navigator.geolocation.getCurrentPosition(function(location){
  var lat = location.coords.latitude;
  var long = location.coords.longitude;
  
  getJSONP(API_URL + lat + ',' + long, 'addTempToSpan');
});

function createWeatherNode(temperature){
  // generated by http://freddyb.github.io/html2dom/
  var docFragment = document.createDocumentFragment();

  var h1 = document.createElement('H1');
  docFragment.appendChild(h1);
  var text = document.createTextNode("Current Temperature: ");
  h1.appendChild(text);

  var span = document.createElement('SPAN');
  h1.appendChild(span);
  var text_0 = document.createTextNode(temperature);
  span.appendChild(text_0);
  var text_1 = document.createTextNode("ºF");
  h1.appendChild(text_1);
  
  return docFragment;
}

  
function addTempToSpan(data) {
  var body = document.body;
  var temperature = data.currently.temperature.toFixed(1);
  
  body.innerHTML = '';
  body.appendChild(createWeatherNode(temperature));
}

function getJSONP(url, cb) {
  var script = document.createElement('script');
  script.src = url + '?callback=' + cb;
  
  document.body.appendChild(script);
}